### ISSUE TITLE
compilation failure

### ISSUE THREAD

**Issue by coret** [IISH/oai4solr#1]
When I tried to compile the oai4solr plugin (mvn clean package) I had to download and install com.springsource.org.mortbay.jetty.server-6.1.9.jar by hand (mvn install:install-file -DgroupId=org.mortbay.jetty -DartifactId=com.springsource.org.mortbay.jetty.server -Dversion=6.1.9 -Dpackaging=jar -Dfile=com.springsource.org.mortbay.jetty.server-6.1.9.jar)

After this compilation gave the following error:

```
  [INFO] Compilation failure

  /tmp/IISH-oai4solr-357e4ff/src/main/java/bootstrap/StartUp.java:[28,24] cannot access org.mortbay.component.AbstractLifeCycle
class file for org.mortbay.component.AbstractLifeCycle not found
        Server server = new Server(port);

  /tmp/IISH-oai4solr-357e4ff/src/main/java/bootstrap/StartUp.java:[34,14] cannot find symbol
symbol  : method start()
location: class org.mortbay.jetty.Server
```

Solved it by adding the following to pom.xml:

```
    <dependency>
        <groupId>org.mortbay.jetty</groupId>
        <artifactId>jetty-util</artifactId>
        <version>6.1.10</version>
    </dependency>
```

**Comment by lwo** [comment]
Thanks for pointing this out coret. I shall try to reproduce the build failure with a cleaned local repository.

**Comment by lwo** [comment]
Fixed by https://github.com/IISH/oai4solr/commit/a9f4f6ced19fff807c9d4d37c227218dddc94a3e

You can download the latest build from:
https://bamboo.socialhistoryservices.org/browse/OAI4SOLR-OAI4SOLR/

I intend to remove the Jetty bootstrap and replace it with a Jetty maven plugin.
