### ISSUE TITLE
Too short timestamp in responseDate

### ISSUE THREAD

**Issue by rolfis** [IISH/oai4solr#11]
I get a short and mangled responseDate like this:
<responseDate>2016-01-0Z</responseDate>

when running all commands like Identify, GetRecord, ListSets etc.

I suspect this has something to do with the LANG locale being "sv_SE.UTF-8".
Any ideas on how to fix it?

Solr version:
4.10.2

Tomcat:
Apache Tomcat/8.0.24

JRE:
1.8.0_45-b14

**Comment by lwo** [comment]
I am not sure yet. Is your element in Identify.xml
OAI-PMH/Identify/granularity:
https://github.com/IISH/oai4solr/blob/4.x-1.0/demo/solr/core0/oai/Identify.xml#L36

set as
YYYY-MM-DDThh:mm:ssZ or YYYY-MM-DD
or something else ?

**Comment by rolfis** [comment]
It's set as:
<granularity>YYYY-MM-DD</granularity>

**Comment by rolfis** [comment]
If I set it to YYYY-MM-DDThh:mm:ssZ makes the responseDate output in this format.

**Comment by lwo** [comment]
Thanks for reporting this @rolfis
Fixed by https://github.com/IISH/oai4solr/commit/fd191d6fb701551d8350ef393a2c62a1b2ecdfdb
