### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by travisLilleberg** [IISH/oai4solr#13]
Hello, when copy-pasting the QueryResponseWriter and requestHandler into my solrconfig file, I get the following error:

> Error creating core [blacklight-core]: Error loading class 'org.socialhistoryservices.solr.oai.OAIQueryResponseWriter'

After a quick search through the code, it appears that you actually want org.socialhistoryservices._api_.oai.OAIRequestHandler, 
and 
org.socialhistoryservices._api_.oai.OAIQueryResponseWriter.

**Comment by lwo** [comment]
Hello Travis,

Thanks for reporting that. I committed the patch:

https://github.com/IISH/oai4solr/commit/d31a36b8fa3fc59e8fdf0964ec7320a6da663c2a
https://github.com/IISH/oai4solr/commit/47001d02c01ab11c35e75e8884ee741ca6ee1f65
https://github.com/IISH/oai4solr/commit/5c7d8c736e80316c6d764deae31d6ce91bfd2697
https://github.com/IISH/oai4solr/commit/926865a7e044cb6c18821379953e46d7e744db57
