### ISSUE TITLE
Build server cannot connect to GitHub

### ISSUE THREAD

**Issue by anjackson** [IISH/oai4solr#2]
Just wanted to check that you know that the build server is having problems connecting to GitHub and hasn't built OAI4SOLR for ten months.  See the errors on this page:
https://bamboo.socialhistoryservices.org/browse/OAI4SOLR-OAI4SOLR/

**Comment by mariomieldijk** [comment]
Hi Thanks, As soon the developer is back from vacation I will bring him it in his attention.

**Comment by lwo** [comment]
Thanks for pointing that out Andy. There have been no commits for about a year now, all though Solr 4 will make that necessary. The error itself occurs when the build server does occasionally has connection disagreements with the git repository.
