### ISSUE TITLE
oai_dc.xsl error

### ISSUE THREAD

**Issue by inghamn** [IISH/oai4solr#4]
The provided oai_dc.xsl includes calls to a saxon function that does not exist.

ERROR:  'The first argument to the non-static Java function 'parse' is not a valid object reference.'
FATAL ERROR:  'Error checking type of the expression 'FilterParentPath(funcall(http://saxon.sf.net/:parse, []), step("child", -1))'.'
           :Error checking type of the expression 'FilterParentPath(funcall(http://saxon.sf.net/:parse, []), step("child", -1))'.
1149 [coreLoadExecutor-4-thread-1] ERROR org.socialhistoryservices.api.oai.OAIRequestHandler  – javax.xml.transform.TransformerConfigurationException: Error checking type of the expression 'FilterParentPath(funcall(http://saxon.sf.net/:parse, []), step("child", -1))'.

**Comment by lwo** [comment]
This xsl example does indeed rely on a Saxon parser for xslt 2 documents. Depending on your mapping approach you may or may not need it. To use xslt 2 functions, download a parser from:
http://repo1.maven.org/maven2/net/sf/saxon/saxon/8.7/saxon-8.7.jar
http://repo1.maven.org/maven2/net/sf/saxon/saxon-dom/8.7/saxon-dom-8.7.jar
and place it in the class path of your tomcat instance.

I.e.
.../webapps/solr/WEB-INF/lib
or /tomcat6/lib
